### ISSUE TITLE
Client conf creation issue on remote host

### ISSUE THREAD

**Issue by tchivert** [brainsys-io/ansible-role-openvpn#2]
This function use the plugin `lookup()`, which only reads files from the control machine.

On `tasks/client.yml` :
```yaml
- name: 'openvpn | create client configuration file'
  template:
    src: "../data/openvpn/client.ovpn.j2"
    dest: "/etc/openvpn/client/{{ item.name }}/{{ item.name }}.ovpn"
  when: openvpn_client is defined
  loop: "{{ openvpn_client }}"
  vars:
    loop_cert: "{{ lookup('file', '/etc/openvpn/client/' + item.name + '/' + item.name + '.crt') }}"
    loop_key : "{{ lookup('file', '/etc/openvpn/client/' + item.name + '/' + item.name + '.key') }}"
    loop_ca  : "{{ lookup('file', '/etc/openvpn/' + ansible_hostname + '/keys/ca.crt') }}"
    loop_ta  : "{{ lookup('file', '/etc/openvpn/' + ansible_hostname + '/keys/ta.key') }}"
  tags: ['openvpn', 'openvpn_client']
```
